import avatar from '@/assets/image/avatar.jpeg'

export const StoreList = [
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
]

export const CategoryList = [
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '蔬菜',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
]

export const GeneralizeList = [
  {
    title: '店员名称1',
    img: avatar,
    gener_money: '12',
    market_money: '22',
  },
  {
    title: '店员名称2',
    img: avatar,
    gener_money: '5',
    market_money: '42',
  },
  {
    title: '店员名称3',
    img: avatar,
    gener_money: '52',
    market_money: '2',
  },
  {
    title: '店员名称4',
    img: avatar,
    gener_money: '1',
    market_money: '52',
  },
  {
    title: '店员名称',
    img: avatar,
    gener_money: '12',
    market_money: '22',
  },
  {
    title: '店员名称',
    img: avatar,
    gener_money: '12',
    market_money: '22',
  },
]

export const ScanList = [
  {
    img: avatar,
    name: 'madedf',
    scan_time: '2019-02-06',
  },
  {
    img: avatar,
    name: 'Limmy',
    scan_time: '2019-03-06',
  },
  {
    img: avatar,
    name: '意志坚定',
    scan_time: '2019-04-06',
  },
  {
    img: avatar,
    name: '一念永恒',
    scan_time: '2019-05-06',
  },
  {
    img: avatar,
    name: '同城',
    scan_time: '2019-06-06',
  },
  {
    img: avatar,
    name: '服务',
    scan_time: '2019-07-06',
  },
]

export const FansList = [
  {
    img: avatar,
    name: 'madedf',
    fans_time: '2019-02-06',
  },
  {
    img: avatar,
    name: 'Limmy',
    fans_time: '2019-03-06',
  },
  {
    img: avatar,
    name: '意志坚定',
    fans_time: '2019-04-06',
  },
  {
    img: avatar,
    name: '一念永恒',
    fans_time: '2019-05-06',
  },
  {
    img: avatar,
    name: '同城',
    fans_time: '2019-06-06',
  },
  {
    img: avatar,
    name: '服务',
    fans_time: '2019-07-06',
  },
]

export const SaleList = [
  {
    img: avatar,
    name: 'madedf',
    sale_time: '2019-02-06',
    consum_money: '2',
  },
  {
    img: avatar,
    name: 'Limmy',
    sale_time: '2019-03-06',
    consum_money: '3',
  },
  {
    img: avatar,
    name: '意志坚定',
    sale_time: '2019-04-06',
    consum_money: '4',
  },
  {
    img: avatar,
    name: '一念永恒',
    sale_time: '2019-05-06',
    consum_money: '5',
  },
  {
    img: avatar,
    name: '同城',
    sale_time: '2019-06-06',
    consum_money: '6',
  },
  {
    img: avatar,
    name: '服务',
    sale_time: '2019-07-06',
    consum_money: '7',
  },
]

export const Groups = [
  {
    img: avatar,
    name: 'madedf',
    new_money: '45',
    sold: '12',
  },
  {
    img: avatar,
    name: 'Limmy',
    new_money: '45',
    sold: '8',
  },
  {
    img: avatar,
    name: '意志坚定',
    new_money: '45',
    sold: '36',
  },
  {
    img: avatar,
    name: '一念永恒',
    new_money: '45',
    sold: '0',
  },
  {
    img: avatar,
    name: '同城',
    new_money: '45',
    sold: '78',
  },
  {
    img: avatar,
    name: '服务',
    new_money: '45',
    sold: '57',
  },
]

export const Reserve = [
  {
    img: avatar,
    name: 'Limmy',
    ding_money: '45',
    way: '到店',
    reserve: '8',
  },
  {
    img: avatar,
    name: '意志坚定',
    ding_money: '45',
    way: '到店',
    reserve: '36',
  },
  {
    img: avatar,
    name: '一念永恒',
    ding_money: '45',
    way: '到店',
    reserve: '0',
  },
]

export const CateringList = [
  {
    img: avatar,
    name: 'Limmy',
    price: '45',
    state: '在售',
    sold: '8',
  },
  {
    img: avatar,
    name: '意志坚定',
    price: '45',
    state: '在售',
    sold: '36',
  },
  {
    img: avatar,
    name: '一念永恒',
    ding_money: '45',
    state: '在售',
    sold: '0',
  },
]
export const ShopManager = [
  {
    tal: '15265478963',
    num: '123456',
    name: '情节和',
    sold: '2',
  },
  {
    tal: '18265477873',
    num: '123456',
    name: '情节和',
    sold: '3',
  },
  {
    tal: '19265478963',
    num: '123456',
    name: '情节和',
    sold: '0',
  },
  {
    tal: '12265478963',
    num: '123456',
    name: '情节和',
    sold: '5',
  },
  {
    tal: '14265478963',
    num: '123456',
    name: '情节和',
    sold: '7',
  },
  {
    tal: '13265558963',
    num: '123456',
    name: '情节和',
    sold: '9',
  },
]

export const MiniFansList = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
]

export const PublicMemberList = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
]

export const FansLists = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
]

export const CouponLists = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
]
