import avatar from '@/assets/image/avatar.jpeg'

export const StoreList = [
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
  {
    title: '店铺1号',
    img: avatar,
    extra: '正常',
  },
]

export const CategoryList = [
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '蔬菜',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
  {
    title: '店铺1号',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
  },
]

export const AssistantList = [
  {
    scan_totalNum: '111',
    fans_totalNum: '652',
    purchase_totalNum: '1235',
    sale_commission: '154',
    generalize_commission: '569',
    start_time: '2015-02-21',
    end_time: '2019-02-21',
    lists: [
      {
        title: '同城百商联盟',
      },
      {
        title: '配送测试',
      },
      {
        title: '餐饮测试',
      },
      {
        title: '团购测试',
      },
      {
        title: '预定测试',
      },
      {
        title: '同城百商联盟',
      },
    ],
  },
]

export const MiniFansList = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
  },
]

export const PublicMemberList = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    tel: '****',
    sex: '未知',
    registerTime: '2019-08-02',
    focus: '2012-12-24',
    lasted: '2019-09-02',
    type: '扫描商家产品二维码',
  },
]

export const FansLists = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
]

export const CouponLists = [
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
  {
    id: 1,
    img: avatar,
    name: '预约打死喉结',
    category: '预定',
    type: '司仪预约',
    system: '移动网页 app 微信',
    total: 100,
    newUser: false,
    startTime: '2019-08-08',
    endTime: '2019-08-09',
    condition: '满100.00减10.00元',
    used: 4,
    enable: false,
  },
]
